#version: "3.8"

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  ingester:
    build: ./ingester
    ports:
      - "8003:8000"

  orchestrator:
    build: ./orchestrator
    ports:
      - "8000:8000"
    depends_on:
      - ingester
      - redis

  renderer:
    build: ./renderer
    ports:
      - "8001:8001"
    volumes:
      - ./renderer/output:/app/output

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - orchestrator

